import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateGroupPDF = (groupName, allExpenses, members, admin) => {
    // We want to keep the PDF receipt clean, so we filter out any bills that have been completely settled.
    // If the number of settled splits is less than the total splits, it means someone still owes money!
    const expenses = allExpenses.filter(exp => {
        const totalSplits = exp.splits?.length || 0;
        const settledCount = exp.settledSplits?.length || 0;
        return settledCount < totalSplits;
    });
    const doc = new jsPDF({
        unit: 'mm',
        format: [80, 200] // receipt width, auto-extend height
    });

    const w = 80;
    const margin = 6;
    const contentW = w - margin * 2;
    let y = 8;

    // ─── Helper functions ────────────────────────────────────────────────
    const centerText = (text, size, style = 'normal') => {
        doc.setFontSize(size);
        doc.setFont('courier', style);
        const tw = doc.getTextWidth(text);
        doc.text(text, (w - tw) / 2, y);
        y += size * 0.45;
    };

    const dottedLine = () => {
        doc.setFontSize(7);
        const dots = '·'.repeat(50);
        const tw = doc.getTextWidth(dots);
        doc.text(dots, (w - tw) / 2, y);
        y += 3;
    };

    const leftRight = (left, right, size = 8) => {
        doc.setFontSize(size);
        doc.setFont('courier', 'normal');
        doc.text(left, margin, y);
        const rw = doc.getTextWidth(right);
        doc.text(right, w - margin - rw, y);
        y += size * 0.45;
    };

    // ─── Receipt Header ──────────────────────────────────────────────────
    doc.setFont('courier', 'bold');

    centerText('SPLITPAY', 10, 'bold');
    y += 1;
    centerText(groupName.toUpperCase(), 8, 'bold');
    y += 2;
    dottedLine();

    centerText('*** SPLIT BILL ***', 12, 'bold');
    y += 1;
    dottedLine();

    // Admin & date
    doc.setFont('courier', 'normal');
    leftRight('ADMIN', admin?.name?.toUpperCase() || 'N/A', 7);
    leftRight('DATE', new Date().toLocaleDateString(), 7);
    leftRight('MEMBERS', String(members?.length || 0), 7);
    y += 2;
    dottedLine();

    // ─── Bill Items ──────────────────────────────────────────────────────
    if (expenses.length === 0) {
        centerText('No bills to display', 8);
        y += 2;
    } else {
        expenses.forEach(exp => {
            const desc = (exp.description || 'Item').toUpperCase();
            const amt = `$${Number(exp.amount).toFixed(2)}`;
            leftRight(desc, amt, 8);

            // Show splits under each item
            if (exp.splits && exp.splits.length > 0) {
                exp.splits.forEach(split => {
                    const name = `  ${(split.user?.name || 'Member').substring(0, 15)}`;
                    const owed = `$${split.amountOwed.toFixed(2)}`;
                    doc.setFontSize(7);
                    doc.setTextColor(100);
                    doc.text(name, margin + 2, y);
                    const rw = doc.getTextWidth(owed);
                    doc.text(owed, w - margin - rw, y);
                    y += 3;
                });
                doc.setTextColor(0);
            }
            y += 1;
        });
    }

    dottedLine();

    // ─── Totals ──────────────────────────────────────────────────────────
    const totalAmount = expenses.reduce((sum, e) => sum + Number(e.amount), 0);
    const settledCount = expenses.reduce((sum, e) => sum + (e.settledSplits?.length || 0), 0);
    const totalSplits = expenses.reduce((sum, e) => sum + (e.splits?.length || 0), 0);

    doc.setFont('courier', 'bold');
    leftRight('SUBTOTAL', `$${totalAmount.toFixed(2)}`, 9);
    y += 1;

    doc.setFont('courier', 'normal');
    leftRight('SETTLED', `${settledCount}/${totalSplits}`, 7);
    y += 2;

    dottedLine();

    doc.setFont('courier', 'bold');
    leftRight('TOTAL AMOUNT', `$${totalAmount.toFixed(2)}`, 10);
    y += 3;

    dottedLine();
    y += 2;

    centerText('THANK YOU FOR SPLITTING!', 8, 'bold');
    y += 2;
    centerText('Generated by SplitPay', 6);
    centerText(new Date().toLocaleString(), 6);

    // Resize page to fit content
    const pageHeight = y + 10;
    doc.internal.pageSize.setHeight(pageHeight);

    doc.save(`${groupName}_SplitBill.pdf`);
};