import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateGroupPDF = (groupName, allExpenses, members, admin) => {
    // 1. Filter out fully settled bills
    const expenses = allExpenses.filter(exp => {
        const totalSplits = exp.splits?.length || 0;
        const settledCount = exp.settledSplits?.length || 0;
        return settledCount < totalSplits;
    });

    // 2. Pre-calculate dynamic height to prevent jsPDF canvas shifting bug
    let calcY = 8;
    calcY += 10; // header
    calcY += 10; // admin & date
    if (expenses.length === 0) {
        calcY += 10;
    } else {
        expenses.forEach(exp => {
            calcY += 4;
            if (exp.splits && exp.splits.length > 0) {
                const unsettledSplits = exp.splits.filter(split => {
                    const userId = split.user?._id || split.user;
                    return !exp.settledSplits?.some(settled => (settled._id || settled) === userId);
                });
                calcY += (unsettledSplits.length * 3);
            }
            calcY += 2;
        });
    }
    calcY += 25; // totals
    calcY += 15; // footer

    const doc = new jsPDF({
        unit: 'mm',
        format: [80, Math.max(100, calcY + 10)] // set height upfront
    });

    const w = 80;
    const margin = 6;
    let y = 8;

    // ─── Helper functions ────────────────────────────────────────────────
    const centerText = (text, size, style = 'normal') => {
        doc.setFontSize(size);
        doc.setFont('courier', style);
        const tw = doc.getTextWidth(text);
        doc.text(text, (w - tw) / 2, y);
        y += size * 0.45;
    };

    const dottedLine = () => {
        doc.setFontSize(7);
        const dots = '·'.repeat(50);
        const tw = doc.getTextWidth(dots);
        doc.text(dots, (w - tw) / 2, y);
        y += 3;
    };

    const leftRight = (left, right, size = 8) => {
        doc.setFontSize(size);
        doc.setFont('courier', 'normal');
        doc.text(String(left), margin, y);
        const rw = doc.getTextWidth(String(right));
        doc.text(String(right), w - margin - rw, y);
        y += size * 0.45;
    };

    // ─── Receipt Header ──────────────────────────────────────────────────
    doc.setFont('courier', 'bold');

    centerText('SPLITPAY', 10, 'bold');
    y += 1;
    centerText(String(groupName).toUpperCase(), 8, 'bold');
    y += 2;
    dottedLine();

    centerText('*** UNSETTLED BILLS ***', 10, 'bold');
    y += 1;
    dottedLine();

    // Admin & date
    doc.setFont('courier', 'normal');
    leftRight('ADMIN', admin?.name?.toUpperCase() || 'N/A', 7);
    leftRight('DATE', new Date().toLocaleDateString(), 7);
    leftRight('MEMBERS', String(members?.length || 0), 7);
    y += 2;
    dottedLine();

    // ─── Bill Items ──────────────────────────────────────────────────────
    if (expenses.length === 0) {
        centerText('No pending bills', 8);
        y += 2;
    } else {
        expenses.forEach(exp => {
            const desc = (exp.description || 'Item').toUpperCase();
            const amt = `Rs ${Number(exp.amount).toFixed(2)}`;
            leftRight(desc, amt, 8);

            // Show unsettled splits under each item
            if (exp.splits && exp.splits.length > 0) {
                const unsettledSplits = exp.splits.filter(split => {
                    const userId = split.user?._id || split.user;
                    return !exp.settledSplits?.some(settled => (settled._id || settled) === userId);
                });

                unsettledSplits.forEach(split => {
                    const name = `  ${(split.user?.name || 'Member').substring(0, 15)}`;
                    const owed = `Rs ${Number(split.amountOwed).toFixed(2)}`;
                    doc.setFontSize(7);
                    doc.setTextColor(100);
                    doc.text(name, margin + 2, y);
                    const rw = doc.getTextWidth(owed);
                    doc.text(owed, w - margin - rw, y);
                    y += 3;
                });
                doc.setTextColor(0);
            }
            y += 1;
        });
    }

    dottedLine();

    // ─── Totals ──────────────────────────────────────────────────────────
    const totalAmount = expenses.reduce((sum, e) => sum + Number(e.amount), 0);
    const settledCount = expenses.reduce((sum, e) => sum + (e.settledSplits?.length || 0), 0);
    const totalSplits = expenses.reduce((sum, e) => sum + (e.splits?.length || 0), 0);

    doc.setFont('courier', 'bold');
    leftRight('SUBTOTAL', `Rs ${totalAmount.toFixed(2)}`, 9);
    y += 1;

    doc.setFont('courier', 'normal');
    leftRight('SETTLED', `${settledCount}/${totalSplits}`, 7);
    y += 2;

    dottedLine();

    doc.setFont('courier', 'bold');
    leftRight('TOTAL AMOUNT', `Rs ${totalAmount.toFixed(2)}`, 10);
    y += 3;

    dottedLine();
    y += 2;

    centerText('THANK YOU FOR SPLITTING!', 8, 'bold');
    y += 2;
    centerText('Generated by SplitPay', 6);
    centerText(new Date().toLocaleString(), 6);

    doc.save(`${groupName}_SplitBill.pdf`);
};
